# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}     
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name : Install node
      working-directory: './my-resume' 
      run: npm ci
    - name : Build gridsome
      working-directory: './my-resume' 
      run: npm run build --if-present
      env:
        CI: true   
    - name: Upload dist folder as an artifact ZIP 
      uses: actions/upload-artifact@master
      with:
        name: static   # Name of the ZIP
        path: './my-resume/dist' 
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
      with:
        dir: './my-resume/dist' 
        repo: dawoe/dawoe.github.io
        branch: master
        token: ${{ secrets.ACCESS_TOKEN }}
